const categoriesData = [
  {
    name: "indoor",
    products: [
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
    ],
  },
  {
    name: "outdoor",
    products: [
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
    ],
  },
  {
    name: "home",
    products: [
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
    ],
  },
  {
    name: "hospitality",
    products: [
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
    ],
  },
  {
    name: "steel",
    products: [
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
    ],
  },
  {
    name: "wood",
    products: [
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood coffee table",
        img: "https://img1.homary.com/filters:format(webp)/mall/file/2022/02/17/5167e7aae0fd45f48217220175d99885.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
      {
        name: "wood sofa",
        img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jIFfkaDTS._SX355_.jpg",
        details: {
          name: "wood coffee table",
          material: "Mahogany wood",
          color: "cherry coral",
          dimensions: {
            width: 118,
            height: 45,
            length: 78,
          },
          weight: 22,
          description: [
            "Smooth and sleek finish design",
            "Made of high quality Wood",
            "Multi-use",
            "It strong and long lasting as well as a melamine finishing",
            "Combatable for Home and offices",
            "Made in Egypt",
          ],
          images: [
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__57540_pe163122_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0835835_pe601383_s5.jpg?f=xs",
            "https://www.ikea.com/eg/en/images/products/lack-coffee-table-black-brown__0258017_pe401973_s5.jpg?f=m",
          ],
        },
      },
    ],
  },
];

export default categoriesData;